### ISSUE TITLE
Cannot run commands in README

### ISSUE THREAD

**Issue by acrellin** [lsst-dm/alert_stream#23]
I'm following the instructions in the README to get an alert stream & consumer running, but keep hitting errors at the [Start producing an alert stream command](https://github.com/lsst-dm/alert_stream/#start-producing-an-alert-stream). I'm running the latest master. Here's my terminal output:
```
➜  alert_stream git:(master) docker-compose up -d
Creating network "alert_stream_default" with the default driver
Creating alert_stream_zookeeper_1 ... done
Creating alert_stream_kafka_1     ... done

➜  alert_stream git:(master) docker build -t "alert_stream" .
Sending build context to Docker daemon  532.5kB
Step 1/13 : FROM python:3.6
 ---> 5281251bf064
Step 2/13 : LABEL maintainer="LSST Alert Production; https://dm.lsst.org/"
 ---> Using cache
 ---> bd1ddff949f6
Step 3/13 : RUN pip install 'confluent-kafka>=0.11.4'
 ---> Using cache
 ---> 07b0c729ed10
Step 4/13 : RUN pip install avro-python3
 ---> Using cache
 ---> e09b01855f92
Step 5/13 : RUN pip install Cython
 ---> Using cache
 ---> 2e0491394d2c
Step 6/13 : RUN pip install fastavro
 ---> Using cache
 ---> 3e7c0b6f12f9
Step 7/13 : RUN pip install numpy
 ---> Using cache
 ---> 410f864a9407
Step 8/13 : WORKDIR /home
 ---> Using cache
 ---> 3ddfad781296
Step 9/13 : RUN git clone https://github.com/lsst-dm/sample-avro-alert.git
 ---> Using cache
 ---> a2d18f8dbfe7
Step 10/13 : RUN mkdir alert_stream
 ---> Using cache
 ---> 875213799b76
Step 11/13 : ADD . /home/alert_stream
 ---> Using cache
 ---> 0d7ee57faa95
Step 12/13 : ENV PYTHONPATH=/home/alert_stream/python:/home/sample-avro-alert/python
 ---> Using cache
 ---> fe7a6c78dcae
Step 13/13 : WORKDIR /home/alert_stream
 ---> Using cache
 ---> 8cb1432518f7
Successfully built 8cb1432518f7
Successfully tagged alert_stream:latest

➜  alert_stream git:(master) docker run -it --rm alert_stream python bin/sendAlertStream.py -h
  
usage: sendAlertStream.py [-h] broker topic

Generates batches of alerts coming from a CCD given template alert content.

positional arguments:
  broker      Hostname or IP and port of Kafka broker.
  topic       Name of Kafka topic stream to push to.

optional arguments:
  -h, --help  show this help message and exit

➜  alert_stream git:(master) docker run -it --rm \                                            
  --network=alert_stream_default \
  -v $PWD/data:/home/alert_stream/data:ro \
  alert_stream python bin/sendAlertStream.py kafka:9092 my-stream
visit: 1574. 	time: 1557940917.0107694
Task exception was never retrieved
future: <Task finished coro=<schedule_delays() done, defined at bin/sendAlertStream.py:30> exception=ValueError('read length must be positive or -1',)>
Traceback (most recent call last):
  File "bin/sendAlertStream.py", line 47, in schedule_delays
    yield from asyncio.ensure_future(delay(wait_time, function, arg))
  File "bin/sendAlertStream.py", line 27, in delay
    return function(*args)
  File "bin/sendAlertStream.py", line 76, in send_visit
    schema, alert_packets = retrieve_alerts(file_data)
  File "/home/sample-avro-alert/python/lsst/alert/packet/io.py", line 40, in retrieve_alerts
    reader = fastavro.reader(fp, reader_schema=reader_schema.definition if reader_schema else None)
  File "fastavro/_read.pyx", line 745, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 700, in fastavro._read.file_reader.__init__
  File "fastavro/_read.pyx", line 564, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 460, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 560, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 408, in fastavro._read.read_map
  File "fastavro/_read.pyx", line 552, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 304, in fastavro._read.read_bytes
ValueError: read length must be positive or -1
```

**Comment by jdswinbank** [comment]
Hello,

Thanks for the problem report!

I'm pretty sure the issue here is that you haven't used [Git LFS](https://git-lfs.github.com) to clone the repository. Could you check?

An easy way to do so is to look at the contents of the files in `data`. If they look something like this 

```
$ cat data/alerts_11577.avro 
version https://git-lfs.github.com/spec/v1
oid sha256:5f8c09d88496e3f7a499229167a57329918fa676bcd15b920f6457311fe77b06
size 23413917
```

then Git LFS is *not* set up properly.

**Comment by acrellin** [comment]
Thanks, using Git LFS to clone the repo fixed the issue.

**Comment by jdswinbank** [comment]
Glad it's working!

I've tweaked things in https://github.com/lsst-dm/sample-avro-alert/pull/6 to generate a more helpful error message if this happens again.
